/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobiblioteca;

import java.sql.Connection;
import java.sql.ResultSet;

/**
 *
 * @author f_mor
 */
public class RegistroAlumnos extends javax.swing.JPanel {

    /**
     * Creates new form RegistroAlumnos
     */
    public RegistroAlumnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombrealumno = new javax.swing.JTextField();
        apellidopat = new javax.swing.JTextField();
        apellidomat = new javax.swing.JTextField();
        rut = new javax.swing.JTextField();
        numeromatriculas = new javax.swing.JTextField();
        dv = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        eliminaralumno = new javax.swing.JButton();
        modificaralumno = new javax.swing.JButton();
        registraralumno = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        idalumnos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaalumnos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(76, 134, 236));

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Datos Alumno", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setText("Nombres");

        jLabel2.setText("Apellido Paterno");

        jLabel3.setText("Apellido Materno");

        jLabel4.setText("Rut");

        jLabel5.setText("Numero Matricula");

        jLabel6.setText("-");

        eliminaralumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        eliminaralumno.setText("Eliminar");
        eliminaralumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaralumnoActionPerformed(evt);
            }
        });

        modificaralumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        modificaralumno.setText("Modificar");
        modificaralumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificaralumnoActionPerformed(evt);
            }
        });

        registraralumno.setBackground(java.awt.SystemColor.inactiveCaption);
        registraralumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrar.png"))); // NOI18N
        registraralumno.setText("Registrar");
        registraralumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registraralumnoActionPerformed(evt);
            }
        });

        jLabel7.setText("ID");

        jScrollPane1.setBackground(java.awt.SystemColor.activeCaption);
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Registro de alumnos"));

        tablaalumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaalumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaalumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaalumnos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(apellidopat, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(54, 54, 54)
                                .addComponent(nombrealumno))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(registraralumno)
                                    .addGap(3, 3, 3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(modificaralumno)
                                .addGap(18, 18, 18)
                                .addComponent(eliminaralumno))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(idalumnos, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(apellidomat, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(rut, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(9, 9, 9)
                                    .addComponent(jLabel6)
                                    .addGap(5, 5, 5)
                                    .addComponent(dv, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(numeromatriculas, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombrealumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(apellidopat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(apellidomat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(numeromatriculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(idalumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registraralumno)
                    .addComponent(modificaralumno)
                    .addComponent(eliminaralumno))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jButton1.setText("Mostrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButton1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registraralumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registraralumnoActionPerformed
        // TODO add your handling code here:
        
        Connection conexion=conectar.abrirConexion();
        
        datosalumno.AgregarAlumno(nombrealumno, apellidopat, apellidomat, rut, dv, numeromatriculas, conexion);
        
        String sql= "select * from alumno";
        ResultSet result=conectar.Consulta(conexion, sql);
        metodosadicionales.MostradDB(result, tablaalumnos);
        conectar.cerrarConexion(conexion);
    }//GEN-LAST:event_registraralumnoActionPerformed

    private void modificaralumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificaralumnoActionPerformed
        // TODO add your handling code here:
        
        Connection conexion=conectar.abrirConexion();
        
        datosalumno.ModificarEstudiante(conexion, idalumnos, nombrealumno, apellidopat, apellidomat, rut, dv, numeromatriculas);
        
        String sql= "select * from alumno";
        ResultSet result=conectar.Consulta(conexion, sql);
        metodosadicionales.MostradDB(result, tablaalumnos);
        conectar.cerrarConexion(conexion);
    }//GEN-LAST:event_modificaralumnoActionPerformed

    private void eliminaralumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaralumnoActionPerformed
        // TODO add your handling code here:
         Connection conexion=conectar.abrirConexion();
         datosalumno.EliminarEstudiante(idalumnos, conexion);
         
        String sql= "select * from alumno";
        ResultSet result=conectar.Consulta(conexion, sql);
        metodosadicionales.MostradDB(result, tablaalumnos);
        conectar.cerrarConexion(conexion);
        
    }//GEN-LAST:event_eliminaralumnoActionPerformed

    private void tablaalumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaalumnosMouseClicked
        // TODO add your handling code here:
        int fila=tablaalumnos.getSelectedRow();
        idalumnos.setText(tablaalumnos.getValueAt(fila, 0).toString());
        rut.setText(tablaalumnos.getValueAt(fila, 1).toString());
        dv.setText(tablaalumnos.getValueAt(fila, 2).toString());
        nombrealumno.setText(tablaalumnos.getValueAt(fila, 3).toString());
        apellidopat.setText(tablaalumnos.getValueAt(fila, 4).toString());
        apellidomat.setText(tablaalumnos.getValueAt(fila, 5).toString());
        numeromatriculas.setText(tablaalumnos.getValueAt(fila, 6).toString());
        
        idalumnos.setEditable(false);
        
    }//GEN-LAST:event_tablaalumnosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection cnx=conectar.abrirConexion();
      
         String sql= "select * from alumno";
        ResultSet result=conectar.Consulta(cnx, sql);
        metodosadicionales.MostradDB(result, tablaalumnos);
        
        conectar.cerrarConexion(cnx);
    }//GEN-LAST:event_jButton1ActionPerformed


    
    Conexion conectar= new Conexion();
    MetodosAdicionales metodosadicionales= new MetodosAdicionales();
    DatosAlumnos datosalumno= new DatosAlumnos();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidomat;
    private javax.swing.JTextField apellidopat;
    private javax.swing.JTextField dv;
    private javax.swing.JButton eliminaralumno;
    private javax.swing.JTextField idalumnos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificaralumno;
    private javax.swing.JTextField nombrealumno;
    private javax.swing.JTextField numeromatriculas;
    private javax.swing.JButton registraralumno;
    private javax.swing.JTextField rut;
    private javax.swing.JTable tablaalumnos;
    // End of variables declaration//GEN-END:variables
}
